name: app
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'
dependencies:
  atomic_design:
    path: packages/atomic_design
  dio: ^5.2.1+1
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  freezed_annotation: ^2.2.0
  go_router: ^9.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  json_annotation: ^4.8.1
  logger: ^1.4.0
  mocktail: ^0.3.0
  palette_generator: ^0.3.3+2
  retrofit: ^4.0.1

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.3.5
  hive_generator: ^2.0.0
  json_serializable: ^6.7.1
  retrofit_generator: ^7.0.6

flutter:

  uses-material-design: true
