name: Flutter CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  build:
    name: Flutter build_runner
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.5'
      - name: Install packages
        run: flutter pub get
        working-directory: ./app
      - name: build_runner
        run: dart pub run build_runner build --delete-conflicting-outputs
        working-directory: ./app
      
  
  test:
    needs: build
    name: Flutter Test
    runs-on: ubuntu-latest
    steps :
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
      - name: Test
        run: flutter test
        working-directory: ./app

    